In [1]:
import pandas as pd

In [4]:
df = pd.read_parquet("../data/processed/bus_delay_simulation.parquet")
df

,trip_id,route_id,stop_id,stop_lat,stop_lon,stop_sequence,normalized_stop_position,scheduled_arrival_unix,gps_timestamp,hour_of_day,day_of_week,route_id_freq,stop_id_freq,trip_id_freq,distance_to_prev_stop_km,prev_delay,rolling_delay_3,delay_minutes
0,10001_08_10,10001,3928,28.703650,77.100518,0,0.000000,1742803800,1742804455,8,4,2250,196,75,0.0000,0.00,0.000000,10.92
1,10001_08_10,10001,3929,28.706167,77.102720,1,0.013514,1742803884,1742804496,8,4,2250,196,75,0.3528,10.92,10.920000,10.20
2,10001_08_10,10001,3930,28.709155,77.105354,2,0.027027,1742803985,1742804575,8,4,2250,196,75,0.4200,10.20,10.560000,9.85
3,10001_08_10,10001,20001,28.706559,77.110366,3,0.040541,1742804121,1742804615,8,4,2250,55,75,0.5677,9.85,10.323333,8.25
4,10001_08_10,10001,20002,28.704488,77.113473,4,0.054054,1742804212,1742804833,8,4,2250,55,75,0.3806,8.25,9.433333,10.36
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3724315,9_09_30,9,2988,28.692750,77.077417,44,0.916667,1742815073,1742815312,11,1,784,326,49,0.4471,0.66,-0.173333,3.99
3724316,9_09_30,9,2989,28.695400,77.073500,45,0.937500,1742815188,1742815312,11,1,784,384,49,0.4825,3.99,0.410000,2.08
3724317,9_09_30,9,2990,28.700500,77.075300,46,0.958333,1742815330,1742815210,11,1,784,326,49,0.5936,2.08,2.243333,-2.00
3724318,9_09_30,9,2991,28.701600,77.075200,47,0.979167,1742815360,1742815444,11,1,784,366,49,0.1227,-2.00,1.356667,1.41
3724319,9_09_30,9,1164,28.703449,77.075009,48,1.000000,1742815409,1742815520,11,1,784,515,49,0.2064,1.41,0.496667,1.87

In [5]:
df.dtypes

trip_id                      object
route_id                      int64
stop_id                       int64
stop_lat                    float64
stop_lon                    float64
stop_sequence                 int64
normalized_stop_position    float64
scheduled_arrival_unix        int64
gps_timestamp                 int64
hour_of_day                   int64
day_of_week                   int64
route_id_freq                 int64
stop_id_freq                  int64
trip_id_freq                  int64
distance_to_prev_stop_km    float64
prev_delay                  float64
rolling_delay_3             float64
delay_minutes               float64
dtype: object

In [7]:
df.head(5)

,trip_id,route_id,stop_id,stop_lat,stop_lon,stop_sequence,normalized_stop_position,scheduled_arrival_unix,gps_timestamp,hour_of_day,day_of_week,route_id_freq,stop_id_freq,trip_id_freq,distance_to_prev_stop_km,prev_delay,rolling_delay_3,delay_minutes
0,10001_08_10,10001,3928,28.703650,77.100518,0,0.000000,1742803800,1742804455,8,4,2250,196,75,0.0000,0.00,0.000000,10.92
1,10001_08_10,10001,3929,28.706167,77.102720,1,0.013514,1742803884,1742804496,8,4,2250,196,75,0.3528,10.92,10.920000,10.20
2,10001_08_10,10001,3930,28.709155,77.105354,2,0.027027,1742803985,1742804575,8,4,2250,196,75,0.4200,10.20,10.560000,9.85
3,10001_08_10,10001,20001,28.706559,77.110366,3,0.040541,1742804121,1742804615,8,4,2250,55,75,0.5677,9.85,10.323333,8.25
4,10001_08_10,10001,20002,28.704488,77.113473,4,0.054054,1742804212,1742804833,8,4,2250,55,75,0.3806,8.25,9.433333,10.36